# Generated by Django 3.2.4 on 2021-06-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wandmind', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poem',
        ),
    ]
